# Generated by Django 4.0.10 on 2024-02-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], default=3),
        ),
    ]
